### ISSUE TITLE
RTSP streaming with depth image

### ISSUE THREAD

**Issue by phamdat09** [stereolabs/zed-gstreamer#26]
Hello,

Do you have any example to stream rgb and depth image via RTSP without lossy the info of depth?

Thanks

**Comment by Myzhar** [comment]
Hi @phamdat09 
you could stream raw depth data without H264 encoding, but sincerely I'm not sure that you can remove the encoding elements from a GStreamer pipeline. Without H264 (or any other encoding elements) the required bandwidth would be really high.

**Comment by phamdat09** [comment]
@Myzhar 
Thank for your reply !!

Is there any way to send raw depth with one encoding element?
