### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by galitgoz** [stereolabs/zed-gstreamer#29]
Hi, 
I am trying to stream RTSP side by side right and left video, but the gstzedsrc organizes it vertically. Any advise how to change it?
Thanks

**Comment by Myzhar** [comment]
The ZED GStreamer is designed to stream stereo couples organized vertically instead of horizontally to improve performances in filtering operations.
If you need side by side images you can modify the zedsrc element or write your own filter that reorganizes the images
