### ISSUE TITLE
No such element or plugin 'zedsrc'

### ISSUE THREAD

**Issue by keli95566** [stereolabs/zed-gstreamer#34]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

Hi there, I tried to run the example on Jetson Nano using ZED SDK 3.5 and Cuda 10.2 following the readme.

Installation was successful and I found all the .so files under : /usr/local/gstreamer-1.0/  folder. But gst-inspect-1.0 couldn't find the installation, output only "No such element or plugin 'zedsrc'".

### Steps to Reproduce

I tried to manually set export the environment variables: GST_PLUGIN_SYSTEM_PATH_1_0, GST_PLUGIN_PATH and GST_PLUGIN_PATH_1_0 to /usr/local/gstreamer-1.0/ 

### Expected Result

Be able to inspect the installed gst streamer

### Actual Result

```
GStreamer-WARNING **: 11:59:59.488: Failed to load plugin '/usr/local/gstreamer-1.0/libgstzedsrc.so': libgstzedmeta.so: cannot open shared object file: No such file or directory

(gst-plugin-scanner:24345): GStreamer-WARNING **: 11:59:59.489: Failed to load plugin '/usr/local/gstreamer-1.0/libgstzedodoverlay.so': libgstzedmeta.so: cannot open shared object file: No such file or directory

(gst-plugin-scanner:24345): GStreamer-WARNING **: 11:59:59.498: Failed to load plugin '/usr/local/gstreamer-1.0/libgstzeddemux.so': libgstzedmeta.so: cannot open shared object file: No such file or directory

(gst-plugin-scanner:24345): GStreamer-WARNING **: 11:59:59.499: Failed to load plugin '/usr/local/gstreamer-1.0/libgstzeddatamux.so': libgstzedmeta.so: cannot open shared object file: No such file or directory

(gst-plugin-scanner:24345): GStreamer-WARNING **: 11:59:59.499: Failed to load plugin '/usr/local/gstreamer-1.0/libgstzedsrc.so': libgstzedmeta.so: cannot open shared object file: No such file or directory

(gst-plugin-scanner:24345): GStreamer-WARNING **: 11:59:59.500: Failed to load plugin '/usr/local/gstreamer-1.0/libgstzedodoverlay.so': libgstzedmeta.so: cannot open shared object file: No such file or directory
No such element or plugin 'zedsrc'
```

### ZED Camera model

ZED Mini

### Environment

```shell
OS:Ubuntu 18.04 LTS
CPU: ARM64 (JETSON NANO)
ZED SDK 3.5
Cuda 10.2
```

### Anything else?

All the other ZED tools work okay

**Comment by dolikemedo** [comment]
I followed the install SDK 3.8, Cuda 11.4 on a Jetson Orin
zedsrc not found
How did you solve it? :)
