### ISSUE TITLE
Add uninstall option to Makefile

### ISSUE THREAD

**Issue by maxpolzin** [stereolabs/zed-gstreamer#35]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

I cannot uninstall the plugin.

### Steps to Reproduce

sudo make uninstall returns:
"""make: *** No rule to make target 'uninstall'.  Stop."""

### Expected Result

Removes the installed files

### Actual Result

Error messages that target uninstall does not exist.

### ZED Camera model

ZED2i

### Environment

```shell
Debian Buster
```

### Anything else?

Please, feel free to close the issue if irrelevant.

**Comment by Myzhar** [comment]
CMake does not provide the `uninstall` feature
