### ISSUE TITLE
zed one src won't work on agx xavier with capture card

### ISSUE THREAD

**Issue by AndreV84** [stereolabs/zed-gstreamer#54]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

gst-inspect-1.0 zedxonesrc

(gst-plugin-scanner:6246): GStreamer-WARNING **: 07:16:58.454: Failed to load plugin '/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstzedxonesrc.so': /lib/aarch64-linux-gnu/libzedarguscapture.so: undefined symbol: vkDestroyImage

### Steps to Reproduce

...
sometimes result look like that
gst-inspect-1.0 | grep zed

(gst-plugin-scanner:3829): GStreamer-WARNING **: 12:17:08.322: Failed to load plugin '/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstzedxonesrc.so': /lib/aarch64-linux-gnu/libzedarguscapture.so: undefined symbol: vkDestroyImage
zeddemux:  zeddemux: ZED Composite Stream Demuxer
zeddatamux:  zeddatamux: ZED Data Video Muxer
zedsrc:  zedsrc: ZED Camera Source
zedodoverlay:  zedodoverlay: ZedOdOverlay
zeddatacsvsink:  zeddatacsvsink: ZED CSV File Sink

### Expected Result

video from zed one gs
on R35.4.1 tegra os

### Actual Result

no video

### ZED Camera model

ZED

### Environment

```shell
zed one x gs
agx xavier + capture card
r35.4.1
```

**Comment by Myzhar** [comment]
@AndreV84 can you try to add `vulkan` as dependency to this line, recompile and install?
https://github.com/stereolabs/zed-gstreamer/blob/master/gst-zedxone-src/lib/CMakeLists.txt#L87

**Comment by AndreV84** [comment]
Hi @Myzhar Thank you for pointing out the line
could you provide the updated line for "target_link_libraries(${libname} ${SPECIAL_OS_LIBS} drm X11)" , please?
