### ISSUE TITLE
RTSP client doesn't work with HD1200 resolution

### ISSUE THREAD

**Issue by jkaniuka** [stereolabs/zed-gstreamer#64]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

I was trying to use RTSP stream from ZED X Camera, but it doesn't work with HD1200

### Steps to Reproduce

1. `gst-zed-rtsp-launch  zedsrc -a 172.16.16.6 camera-sn=44073968  camera-fps=60 camera-resolution=2 ! autovideoconvert ! nvvidconv ! nvv4l2h264enc ! rtph264pay pt=96 name=pay0`
2. `gst-launch-1.0 playbin uri=rtsp://172.16.16.6:8554/zed-stream uridecodebin0::source::latency=0`

### Expected Result

I expected RTSP stream to be displayed on the client side.

### Actual Result

Error on client's side:

```bash
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Progress: (open) Opening Stream
Pipeline is PREROLLED ...
Prerolled, waiting for progress to finish...
Progress: (connect) Connecting to rtsp://172.16.16.6:8554/zed-stream
Progress: (open) Retrieving server options
Progress: (open) Retrieving media info
ERROR: from element /GstPlayBin:playbin0/GstURIDecodeBin:uridecodebin0/GstRTSPSrc:source: Unhandled error
Additional debug info:
../gst/rtsp/gstrtspsrc.c(6795): gst_rtspsrc_send (): /GstPlayBin:playbin0/GstURIDecodeBin:uridecodebin0/GstRTSPSrc:source:
Service Unavailable (503)
ERROR: pipeline doesn't want to preroll.
Setting pipeline to NULL ...
Freeing pipeline ...
```

### ZED Camera model

ZED

### Environment

```shell
ZED Box Orin NX 16 GB with GMSL2
ZED SDK for JetPack 6.0 GA (L4T 36.3) 4.2 (Jetson Orin, CUDA 12.2)
```

**Comment by Myzhar** [comment]
Fixed with https://github.com/stereolabs/zed-gstreamer/pull/66
