### ISSUE TITLE
Side by side option in stream-type argument 

### ISSUE THREAD

**Issue by jkaniuka** [stereolabs/zed-gstreamer#65]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, bug report, or anything other than a feature request directly related to this project.

### Proposal

I would like to be able to display images side by side - now there is only an option to put one on top of the other (`stream-type=2`)

**Comment by Myzhar** [comment]
This feature is currently unavailable and will not be added in the future due to data optimization concerns.
